### ISSUE TITLE
Can't register on the demo site

### ISSUE THREAD

**Issue by lediable** [JorgenSolli/Logit#1]
Hello!

I want to test Logit but I got this error:

(1/1) ClientException
Client error: `POST https://api.mailgun.net/v3/mail.jorgensolli.no/messages.mime` resulted in a `404 NOT FOUND` response:
{
"message": "Domain not found: mail.jorgensolli.no"

**Comment by JorgenSolli** [comment]
Hey, lediable. Sorry for the late reply. I havent been notified of your post for some reason.
I havent set up a proper mailing host for email-verification yet. I will just manually verify your account later today :) 

edit: If your email is "file[...]@gmail.com" then you can log in now.
